# Regenerate dev/ha-config-seed/ from the currently populated dev/ha-config/.
#
# Use this after:
#   - A Home Assistant version bump (`.storage/` schema shifted).
#   - A Smart Plants schema/model change that alters config_entries or storage.
#   - Any deliberate change to the seeded demo (new demo plants, new dashboard).
#
# Prerequisite: the live rig (ha-up.ps1 -Expose) has been onboarded, Smart
# Plants added, any desired demo data created, and then STOPPED (ha-down.ps1)
# so state has flushed to disk. Running against a live container risks copying
# a half-written .storage/ file.
#
# The seed intentionally excludes runtime state (DB, logs, deps, run lock)
# and refresh tokens so no long-lived credential ships in git. The password
# for the seeded owner (admin / admin) is loopback-only per docker-compose.ha.yml
# and documented in docs/development/local-ha-testing.md.

[CmdletBinding()]
param()
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$Runtime = Join-Path $RepoRoot "dev\ha-config"
$Seed    = Join-Path $RepoRoot "dev\ha-config-seed"

if (-not (Test-Path $Runtime)) { throw "dev/ha-config/ does not exist. Run ha-up.ps1 -Expose, onboard, ha-down.ps1 first." }
# HA never deletes .ha_run.lock (it holds a file lock on it), so the file's
# presence says nothing; check the rig container instead.
if (docker ps -q --filter "name=^smart-plants-ha$") {
    throw "The smart-plants-ha container is still running. Stop with ha-down.ps1 first."
}

# .storage keys worth seeding (identity, auth, integration, layout).
$StorageKeep = @(
    "auth",
    "auth_provider.homeassistant",
    "onboarding",
    "person",
    "core.config_entries",
    "core.device_registry",
    "core.entity_registry",
    "core.area_registry",
    "core.uuid",
    "homeassistant.exposed_entities",
    "http",
    "lovelace_dashboards",
    "lovelace.map"
)

$SeedStorage = Join-Path $Seed ".storage"
if (Test-Path $SeedStorage) { Remove-Item -Recurse -Force $SeedStorage }
New-Item -ItemType Directory -Path $SeedStorage | Out-Null

foreach ($k in $StorageKeep) {
    $src = Join-Path $Runtime ".storage\$k"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $SeedStorage $k)
    } else {
        Write-Host ("  skip (not present in runtime): " + $k)
    }
}

# .HA_VERSION pins the schema level the seed matches; HA refuses to boot a
# seed newer than the container image.
$verSrc = Join-Path $Runtime ".HA_VERSION"
if (Test-Path $verSrc) { Copy-Item $verSrc (Join-Path $Seed ".HA_VERSION") -Force }

# Strip long-lived refresh tokens from auth so cloners cannot silently reuse
# the local session that generated this seed. Passwords are hashed in
# auth_provider.homeassistant and must be regenerated by editing this script
# if you rotate them.
$authFile = Join-Path $SeedStorage "auth"
if (Test-Path $authFile) {
    $auth = Get-Content $authFile -Raw | ConvertFrom-Json
    $auth.data.refresh_tokens = @()
    # The system content user is only reachable through its refresh token,
    # which is stripped above. Drop the user as well (http.auth, which points
    # at the token, is not seeded) so HA creates exactly one on first boot.
    $auth.data.users = @($auth.data.users | Where-Object {
        -not ($_.system_generated -and $_.name -eq "Home Assistant Content")
    })
    $json = $auth | ConvertTo-Json -Depth 20
    [IO.File]::WriteAllText($authFile, $json, [Text.UTF8Encoding]::new($false))
}

Write-Host ""
Write-Host "Seed regenerated at: $Seed"
Write-Host "Review git diff, then commit."
